{
 "title": "Submission Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 1.0 * COUNT(score) / COUNT(*)\nFROM generators"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT AVG(score)\nFROM tasks" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(score)\nFROM tasks"
    },
    { "rawSql": "SELECT COUNT(*)\nFROM tasks" }
   ]
  },
  {
   "title": "Time spent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Time remaining",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Task scores",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT score AS \"Score\"\nFROM tasks\nWHERE score IS NOT NULL"
    }
   ]
  },
  {
   "title": "Task times",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT seconds AS \"Time (s)\"\nFROM tasks\nWHERE seconds IS NOT NULL"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"ID\", generator AS \"Generator\", score AS \"Score\", seconds AS \"Time (s)\"\nFROM tasks\nWHERE generator IS NOT NULL\nORDER BY id"
    }
   ]
  },
  {
   "title": "Best generators",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT generator AS \"Generator\", COUNT(*) AS \"Count\"\nFROM tasks\nWHERE generator IS NOT NULL\nGROUP BY generator\nORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Generator scores",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT generator AS \"Generator\", MIN(score) AS \"Min score\", MAX(score) AS \"Max score\", AVG(score) AS \"Mean score\"\nFROM generators\nWHERE score IS NOT NULL\nGROUP BY generator\nORDER BY AVG(score) DESC"
    }
   ]
  },
  {
   "title": "Generator times",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT generator AS \"Generator\", MIN(seconds) * 1000 AS \"Min time (ms)\", MAX(seconds) * 1000 AS \"Max time (ms)\", AVG(seconds) * 1000 AS \"Mean time (ms)\"\nFROM generators\nWHERE seconds IS NOT NULL\nGROUP BY generator\nORDER BY AVG(seconds) DESC"
    }
   ]
  }
 ]
}